# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField()),
                ('hashtags', models.ManyToManyField(to='tweet_monitor.Hashtag')),
            ],
        ),
    ]
